export const BUTTON_PRESSED_OPACITY = 0.9
export const SPOTIFY_BASE_URL = "https://accounts.spotify.com"

export const COLORS = {
  PRIMARY: "#42C83C",
  SECONDARY: "#2C2C2C",
  TEXT_GRAY: "#DADADA",
  AUTH_BACKGROUND: "#1C1B1B",
  APP_TAB_BAR_BACKGROUND: "#343434",
  APP_PROMO_TEXT: "#FBFBFB",
  APP_CATEGORY_TEXT: "#DBDBDB",
  APP_CATEGORY_DISABLED_TEXT: "#616161",
  APP_CATEGORY_ARTIST_INFO: "#E1E1E1",
  APP_PLAYLIST_SEE_MORE: "#C6C6C6",
  APP_PLAYLIST_TRACK_TEXT: "#D6D6D6"
}