export const BUTTON_PRESSED_OPACITY = 0.9
export const SPOTIFY_BASE_URL = "https://accounts.spotify.com"

export const COLORS = {
  PRIMARY: "#42C83C",
  TEXT_GRAY: "#DADADA",
  AUTH_BACKGROUND: "#1C1B1B",
  APP_TAB_BAR_BACKGROUND: "#343434",
  APP_PROMO_TEXT: "#FBFBFB",
  APP_CATEGORY_TEXT: "#DBDBDB",
  APP_CATEGORY_DISABLED_TEXT: "#616161"
}